

// Geography

Table communities {
  id integer [primary key]
  fips_code varchar [note: "Federal Information Processing Series (FIPS)"]
  name varchar
  regional_corporation_fips_code integer
  borough_fips_code integer
  grid_id integer
  ansi_code varchar [note: "American National Standards Institute (ANSI)"]
  dcra_code varchar [note: "Alaska Division of Community and Regional Affairs (DCRA)"]
  latitude double
  longitude double
  pce_eligible bool
  pce_active bool
  geometry geometry
  village_corp_id integer [note: "nope?"]
}


// Socioeconomic

Table transportation {
  // from DBT dcra.l1_transportation with booleans
  id integer [primary key]
  community_fips_code varchar
  airport bool
  harbordock bool
  stateferry bool
  cargobarge  bool
  roadconnection bool
  coastal bool
  road_or_ferry bool
  description varchar
}
Ref: transportation.community_fips_code - communities.fips_code


Table population_ages{
  // from DBT census.l1_populations_ages
  id integer [primary key]
  community_fips_code varchar
  e_pop_age_total integer
  m_pop_age_total double
  e_pop_age_under_5 integer
  all_the_data double
}
Ref: population_ages.community_fips_code - communities.fips_code

Table populations {
  id integer [primary key] 
  fips_code integer [note: "community?"]
  total_population integer
}
Ref: populations.fips_code - communities.fips_code

Table taxes {
  // AEDG link to "Alaska Taxable Database" is 404. 
  // Find replacement?
  id integer [primary key]
  community_fips_code varchar
  property_tax double
  sales_tax double
  other_tax double
  total_tax double
  tax_per_capita double
  tax_year year
}
Ref: taxes.community_fips_code - communities.fips_code

Table dol_places {
  // DOL places table
  id integer [primary key]
  community_fips_code varchar
  //totalpop double
  white double
  black double
  native double
  asian double
  pacisland double
  other double
  two_plus double
  hispanic double
  natalncomb double
  grpqtrs double
  houseunits double
  vacant double
  occupied double
}
Ref: dol_places.community_fips_code - communities.fips_code

Table employment {
  id integer [primary key]
  community_fips_code varchar
  residents_employed integer
  unemployment_claimants integer
  measurement_year year
}
Ref: employment.community_fips_code - communities.fips_code 

Table schools {
  id integer [primary key]
  community_fips_code varchar
  school_district varchar
  enrollment integer [note: "don't have yet"]
  enrollment_year year [note: "don't have yet"]
}
Ref: schools.community_fips_code - communities.fips_code 

// Energy 

Table communities_pce {
  // separate rows for each report with multiple
  // communities filing together
  // some from Jesse's identities table
  id integer [primary key]
  community_fips_code varchar
  pce_community_code integer [note: "AKA PJ Code, Acct, PCE ID, etc"]
  pce_community_name varchar [note: "can contain multiple community names"]
  pce_operator_name varchar [note: "utility but maybe different string"]
  utility_id integer
  interconnected bool
}
Ref: communities_pce.community_fips_code > communities.fips_code
//Ref: community_pce.utility_id - electric_utility.id


Table fuel_price_reports {
  // DOL places table
  id integer [primary key]
  community_fips_code varchar
  all_the_data double
}
Ref: fuel_price_reports.community_fips_code > communities.fips_code

Table capacity {
  id integer [primary key]
  grid_id integer
  capacity_mw double
  fuel_type varchar [note: "should be a normalized table of standard terms"]
  year integer
}
Ref: communities.grid_id > capacity.grid_id

Table yearly_generation {
  id integer [primary key]
  grid_id integer
  net_generation_mwh integer
  fuel_type varchar [note: "should be a normalized table of standard terms"]
  year integer
}
Ref: communities.grid_id > yearly_generation.grid_id

