[project]
name = "dowl"
version = "0.1.0"
description = "Quickie script to read tables from Excel and write CSv files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
